name: Builder

on:
  push:
    branches: ['main']

jobs:
  build:
    permissions: write-all
    name: Build my project âœ¨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ˜¶â€ğŸŒ«ï¸
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Clean Docker
        run: |
          docker system prune --all --force    
      - name: Cashing... ğŸ‘¾
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Building project... ğŸ’ª
        id: unity_build               
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          versioning: Semantic
          buildName: ${{vars.GAME_NAME}}
          targetPlatform: StandaloneWindows64

    
      - name: Heres new version ğŸ§™â€â™‚ï¸
        run: |
          echo "buildVersion from builder: '${{ steps.unity_build.outputs.buildVersion }}'"
          if [ -z "${{ steps.unity_build.outputs.buildVersion }}" ]; then
            echo "ERROR: buildVersion is empty!"
            exit 1
          fi

      - name: Creating zip-file... ğŸ”¥
        uses: ihiroky/archive-action@v1
        with:
          root_dir: build
          file_path: ../build.zip

      - name: Create release ğŸ¥
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.unity_build.outputs.buildVersion }}
          release_name: New Release ${{ steps.unity_build.outputs.buildVersion }}
          body: "Automated release created by CI"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Adding build to release ğŸ¥³
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ../build.zip
          asset_name: ${{vars.GAME_NAME}}-win-v${{ steps.unity_build.outputs.buildVersion }}.zip
          asset_content_type: application/zip
